### 查询服务
GET http://127.0.0.1:9000/arver/ecommerce-nacos-client/nacos-client/service-instance?serviceId=e-commerce-nacos-client
Accept: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEsXCJ1c2VybmFtZVwiOlwiYXJ2ZXJcIn0iLCJqdGkiOiJhZDRjOTliMS1kNzRhLTQzZTktYjRlYS0wMTEwMDg0MDkzNzkiLCJleHAiOjE2NTE4NTE2MTh9.BMIG4YY8Vw5Xar9hCoFveQzZFFzoB0OaJze9tod9fiOwLotYAX3vxFB03I3y9FwB_15Hm_UvQ1amBwcLtQqFk25RBCTeOJRm0OxeJJSkYrATlJeAwwjd7mqvPbsJg5EAIDype_NKvdMH6PHJalMMspWQsJPBcgdfV_ddqNt986E1cE3Uq3TG2UKqGcabSHN2EL_qh-IfdJcN2FEOBsXCIpw3JkrQ5UAZ4GfQHthpMchx1LxsPMI8IybkwJig6mbilqEpE0AVxTZOFgKeWB1lZ4xWbCmNnxbUo2pkidhjjXj3eq_KOLurZKd6Peb7a14g223YnRbRJBw5G7mJbuJP_A
token: arver