### 查询服务
GET http://127.0.0.1:9000/arver/ecommerce-nacos-client/nacos-client/service-instance?serviceId=e-commerce-nacos-client
Accept: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEsXCJ1c2VybmFtZVwiOlwiYXJ2ZXJcIn0iLCJqdGkiOiI2MGVjNWI2Yy1iMDFkLTQwZjUtYjZhNS0wM2FkZDdlZjllN2IiLCJleHAiOjE2NTE0NzI3OTl9.OlkJ-2kFkDsBcdeHRx2v3mXYBAXiUYEgb4saRGUKXxJ_5JuK0KEo2kd2SPIPUtXqwxvtbI0GrkwIRpYjd-yPtEP0O3tuOf9hqfjn_3PpLzjk4Kqj6v4c3W1BqkzlnqvDzy22ooh_jCTkKOy8MLVo66xdj1XMdqoWY5PQTtJj_ZDQ0cBtOBBW5pZ_3901gHOSa65hBMIRTWOHGnPLl9_Ek2-Ql_GEiUM9bt7q0bpS1yqY4xxXXAxYMNfwJCaqkZ1nsAOOpyyGE8vC8avAj7Vga2Dc97Hc6GsVsp81209UPiedKAPwemjLNUsNpVgAyPGO-qlgURIrvuSChsFjDJeeDw
token: arver